name: Build PS5 Game Compressor

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bash \
            build-essential \
            clang-18 \
            lld-18 \
            llvm-18 \
            wget \
            unzip \
            xxd \
            python3 \
            python3-pyelftools \
            pkg-config \
            zlib1g-dev \
            cmake \
            meson \
            socat

     - name: Download PS5 Payload SDK
  run: |
    wget https://github.com/ps5-payload-dev/sdk/releases/latest/download/ps5-payload-sdk.zip
    sudo unzip -q ps5-payload-sdk.zip -d /opt

- name: Install zlib into SDK
  run: |
    git clone https://github.com/madler/zlib.git
    cd zlib

    CC=/opt/ps5-payload-sdk/bin/prospero-clang \
    AR=/opt/ps5-payload-sdk/bin/prospero-ar \
    RANLIB=/opt/ps5-payload-sdk/bin/prospero-ranlib \
    ./configure --static

    make -j$(nproc)

    sudo mkdir -p /opt/ps5-payload-sdk/include
    sudo mkdir -p /opt/ps5-payload-sdk/lib

    sudo cp zlib.h zconf.h /opt/ps5-payload-sdk/include/
    sudo cp libz.a /opt/ps5-payload-sdk/lib/

- name: Build
  env:
    PS5_PAYLOAD_SDK: /opt/ps5-payload-sdk
  run: |
    make
